name: deploy

on:
  push:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: |
        hugo
        mv static/icon/* public/
        
    - name: Deploy Github Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

    - name: Deploy File To Server
      uses: wlixcc/SFTP-Deploy-Action@v1.0 
      with:  
        username: 'root'
        server: ${{ secrets.HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './public/*'
        remote_path: '/usr/env/nginx/html/'
