name: deploy_blog

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: ssh-command
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /usr/env
            ls -a
          host: ${{ secrets.HOST }}
          user: root        
          pass: ${{ secrets.PASS }}
