name: deploy_blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
